require('dotenv').config();
const express  = require('express');
const cors     = require('cors');
const helmet   = require('helmet');
const morgan   = require('morgan');
const path     = require('path');
const fs       = require('fs');
const rateLimit = require('express-rate-limit');
const resumeRoutes    = require('./routes/resume');
const interviewRoutes = require('./routes/interview');
const healthRoutes    = require('./routes/health');
const app  = express();
const PORT = process.env.PORT || 5000;
const uploadsDir = path.join(__dirname, 'uploads');
if (!fs.existsSync(uploadsDir)) fs.mkdirSync(uploadsDir, { recursive: true });
app.use(cors({ origin: true, methods: ['GET','POST','PUT','DELETE','OPTIONS'], allowedHeaders: ['Content-Type','Authorization'], credentials: true }));
app.use(helmet({ crossOriginResourcePolicy: false }));
const limiter = rateLimit({ windowMs: 15*60*1000, max: 100, standardHeaders: true, legacyHeaders: false });
app.use('/api/', limiter);
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));
app.use(morgan('dev'));
app.get('/', (req, res) => res.json({ status: 'ok', message: 'ResumeAI API running' }));
app.use('/api/health',    healthRoutes);
app.use('/api/resume',    resumeRoutes);
app.use('/api/interview', interviewRoutes);
app.use((err, req, res, next) => { console.error('[ERROR]', err.message); res.status(err.status||500).json({ error: err.message||'Internal server error' }); });
app.listen(PORT, () => { console.log(`\n🚀 ResumeAI Backend running on port ${PORT}\n   Gemini: ${process.env.GEMINI_API_KEY ? '✓ configured' : '✗ missing'}\n`); });
module.exports = app;
